import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Grid,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  TextField,
  Chip,
  IconButton,
  Tooltip,
  Avatar,
} from '@mui/material';
import {
  Add,
  Search,
  Download,
  Visibility,
  Send,
  CheckCircle,
  Pending,
  Error,
  Description,
  FilterList,
} from '@mui/icons-material';
import { DataGrid, GridColDef } from '@mui/x-data-grid';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';

export default function DocumentLibrary() {
  const navigate = useNavigate();
  const [searchTerm, setSearchTerm] = useState('');
  const [typeFilter, setTypeFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  // Mock data
  const documents = [
    {
      id: '1',
      documentNumber: 'OFFER2024001',
      title: 'Offer Letter - John Doe',
      type: 'offer-letter',
      employee: 'John Doe',
      employeeId: 'EMP001',
      status: 'generated',
      generatedBy: 'HR Admin',
      generatedAt: '2024-12-01T10:00:00Z',
      downloadUrl: 'https://example.com/doc1.pdf',
    },
    {
      id: '2',
      documentNumber: 'EXP2024001',
      title: 'Experience Letter - Sarah Wilson',
      type: 'experience-letter',
      employee: 'Sarah Wilson',
      employeeId: 'EMP002',
      status: 'sent',
      generatedBy: 'HR Manager',
      generatedAt: '2024-11-28T14:30:00Z',
      downloadUrl: 'https://example.com/doc2.pdf',
    },
    {
      id: '3',
      documentNumber: 'REL2024001',
      title: 'Relieving Letter - Mike Johnson',
      type: 'relieving-letter',
      employee: 'Mike Johnson',
      employeeId: 'EMP003',
      status: 'pending-approval',
      generatedBy: 'HR Admin',
      generatedAt: '2024-11-30T09:15:00Z',
    },
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'generated': return 'success';
      case 'sent': return 'info';
      case 'pending-approval': return 'warning';
      case 'draft': return 'default';
      case 'rejected': return 'error';
      default: return 'default';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'generated': return <CheckCircle />;
      case 'sent': return <Send />;
      case 'pending-approval': return <Pending />;
      case 'rejected': return <Error />;
      default: return <Description />;
    }
  };

  const columns: GridColDef[] = [
    {
      field: 'document',
      headerName: 'Document',
      width: 300,
      renderCell: (params) => (
        <Box>
          <Typography variant="subtitle2" fontWeight={600}>
            {params.row.title}
          </Typography>
          <Typography variant="caption" color="text.secondary">
            {params.row.documentNumber}
          </Typography>
        </Box>
      ),
    },
    {
      field: 'type',
      headerName: 'Type',
      width: 150,
      renderCell: (params) => (
        <Chip
          label={params.value.replace('-', ' ')}
          size="small"
          variant="outlined"
          sx={{ textTransform: 'capitalize' }}
        />
      ),
    },
    {
      field: 'employee',
      headerName: 'Employee',
      width: 200,
      renderCell: (params) => (
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Avatar sx={{ width: 24, height: 24, fontSize: '0.8rem' }}>
            {params.row.employee.charAt(0)}
          </Avatar>
          <Box>
            <Typography variant="body2" fontWeight={500}>
              {params.row.employee}
            </Typography>
            <Typography variant="caption" color="text.secondary">
              {params.row.employeeId}
            </Typography>
          </Box>
        </Box>
      ),
    },
    {
      field: 'status',
      headerName: 'Status',
      width: 150,
      renderCell: (params) => (
        <Chip
          icon={getStatusIcon(params.value)}
          label={params.value.replace('-', ' ')}
          size="small"
          color={getStatusColor(params.value) as any}
          sx={{ textTransform: 'capitalize' }}
        />
      ),
    },
    {
      field: 'generatedBy',
      headerName: 'Generated By',
      width: 150,
    },
    {
      field: 'generatedAt',
      headerName: 'Generated Date',
      width: 150,
      renderCell: (params) => format(new Date(params.value), 'MMM dd, yyyy'),
    },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 150,
      sortable: false,
      renderCell: (params) => (
        <Box>
          <Tooltip title="View Document">
            <IconButton size="small">
              <Visibility />
            </IconButton>
          </Tooltip>
          {params.row.downloadUrl && (
            <Tooltip title="Download">
              <IconButton size="small">
                <Download />
              </IconButton>
            </Tooltip>
          )}
          {params.row.status === 'generated' && (
            <Tooltip title="Send Email">
              <IconButton size="small" color="primary">
                <Send />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      ),
    },
  ];

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Box>
          <Typography variant="h4" fontWeight={600} gutterBottom>
            Document Library
          </Typography>
          <Typography variant="body1" color="text.secondary">
            Manage generated documents and templates
          </Typography>
        </Box>
        
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button
            variant="outlined"
            onClick={() => navigate('/documents/templates')}
          >
            Manage Templates
          </Button>
          <Button
            variant="contained"
            startIcon={<Add />}
            onClick={() => navigate('/documents/generate')}
          >
            Generate Document
          </Button>
        </Box>
      </Box>

      {/* Filters */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Grid container spacing={3} alignItems="center">
            <Grid item xs={12} md={4}>
              <TextField
                fullWidth
                label="Search documents"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                InputProps={{
                  startAdornment: <Search sx={{ mr: 1, color: 'action.active' }} />,
                }}
              />
            </Grid>
            <Grid item xs={12} md={3}>
              <FormControl fullWidth>
                <InputLabel>Document Type</InputLabel>
                <Select
                  value={typeFilter}
                  onChange={(e) => setTypeFilter(e.target.value)}
                  label="Document Type"
                >
                  <MenuItem value="">All Types</MenuItem>
                  <MenuItem value="offer-letter">Offer Letter</MenuItem>
                  <MenuItem value="experience-letter">Experience Letter</MenuItem>
                  <MenuItem value="relieving-letter">Relieving Letter</MenuItem>
                  <MenuItem value="salary-certificate">Salary Certificate</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={3}>
              <FormControl fullWidth>
                <InputLabel>Status</InputLabel>
                <Select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  label="Status"
                >
                  <MenuItem value="">All Status</MenuItem>
                  <MenuItem value="draft">Draft</MenuItem>
                  <MenuItem value="pending-approval">Pending Approval</MenuItem>
                  <MenuItem value="generated">Generated</MenuItem>
                  <MenuItem value="sent">Sent</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={2}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<FilterList />}
                onClick={() => {
                  setSearchTerm('');
                  setTypeFilter('');
                  setStatusFilter('');
                }}
              >
                Clear
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* Documents Table */}
      <Card>
        <CardContent>
          <Box sx={{ height: 600, width: '100%' }}>
            <DataGrid
              rows={documents}
              columns={columns}
              initialState={{
                pagination: {
                  paginationModel: { page: 0, pageSize: 10 },
                },
              }}
              pageSizeOptions={[10, 25, 50]}
              disableRowSelectionOnClick
              sx={{
                border: 'none',
                '& .MuiDataGrid-cell:hover': {
                  color: 'primary.main',
                },
                '& .MuiDataGrid-row:hover': {
                  backgroundColor: 'action.hover',
                  cursor: 'pointer',
                },
              }}
            />
          </Box>
        </CardContent>
      </Card>
    </Box>
  );
}